# Generated by Django 5.0.6 on 2024-06-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='company_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
