# Generated by Django 5.0.6 on 2024-06-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='company',
            new_name='record',
        ),
    ]
