# Generated by Django 5.0.6 on 2024-06-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_comment_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='RecordComment',
        ),
    ]
