# Generated by Django 5.0.6 on 2024-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_record_web_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='web_site',
            field=models.URLField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
    ]
